### ISSUE TITLE
Documentation on lexical or reverse lexical ordering

### ISSUE THREAD

**Issue by lelemmen** [GQCG/bmqc#10]
In `next_bitset_permutation`, we are producing strings according to a lexical ordering, but the addressing scheme produces strings according to reverse lexical ordering.

We should decide if we want the `next_bitset_permutation` algorithm to give strings according to reverse lexical ordering as well.

**Comment by tmhuysen** [comment]
Given, `next_bitset_perumation` and the bit string "001". Two permutations will result in "010" and "100" similarly the order which addressing scheme (with `fetchAddress`) produces the 0th, 1st and 2nd is "001" "010" "100" respectively, is this not the same?

**Comment by lelemmen** [comment]
Given the following occupation number vectors: `011`, `101` and `110`, of which the integer representations are 3, 5 and 6, respectively: recall that the least significant bit is on the right. This means that, according to lexical ordering we have `011` <`101` <`110`.

On the other hand, the ordering described by Helgaker assigns the following creation operator strings for this example: "23", "13" and "12" respectively (in which 2 stands for the creation operator for orbital 2 and similarly for 1 and 3). Using his recipe to decide which string comes after or before an other, we get "23" > "13" > "12", which is clearly the reverse of the previous example.

I think the issue I have is related to the having the least significant bit on the right, but the orbitals are ordered from left to right which means that the largest orbital index is on the right.

Indeed, there is no problem with the algorithms, but we should be more clear in our documentation.

**Comment by lelemmen** [comment]
That is correct: as I said there is no internal problem in the code: it all does the same, it's just the documentation that needs some updating.

**Comment by lelemmen** [comment]
Closing this issue and bringing it over to the GQCP issues because we're archiving this repository.
