### ISSUE TITLE
Re-introduce stand-alone unsigned manipulations?

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/bmqc#27]
The stand-alone unsigned manipulations are not useless, any thoughts on re-introducing them to the library?

**Comment by tmhuysen** [comment]
I just copied next_bitsetpermutation

**Comment by tmhuysen** [comment]
I was about to use the next_bitset_permutation without the class wrapper.

**Comment by lelemmen** [comment]
Could you explain why you wouldn't want to use a `SpinString<unsigned>`?

**Comment by tmhuysen** [comment]
Currently the wrapper is just used for the permutation, might be redundant. Other operations are not performant enough.

**Comment by lelemmen** [comment]
Shouldn't we incorporate the faster algorithms in #24 or #19 then?

**Comment by tmhuysen** [comment]
#24 and #19 are too specific, they incorporate the calculations for the positions something that is not required for programs like valence bond theory. But you're correct that these can in someway be incorporated in wrapper classes.

**Comment by lelemmen** [comment]
Closing this issue and bringing it over to the GQCP issues because we're archiving this repository.
