### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by twhitehead** [GQCG/bmqc#31]
As someone trying to build this for one of our users, it would be really great if you could tag some more releases (and in all your other packages too).

Thanks!  -Tyson

**Comment by lelemmen** [comment]
Hi Tyson (@twhitehead)! Thanks for your interest in our libraries. I can see that our 'releases' on the GitHub releases tab are pretty outdated, thanks for pointing this out. From now on, we'll update these releases accordingly.

In the mean time, the latest release can always be cloned from the master branches using for example `git clone https://github.com/GQCG/bmqc.git --branch master --single-branch`.

**Comment by twhitehead** [comment]
Thanks.  Much appreciated.

I could see there were version numbers in the CMake files, but it wasn't entirely clear where I should consider the corresponding cut points to be in the commits (mostly I just wanted to assign a number that would increment for the purposes of updating and package management).

In the end I just took your master branches and tagged them with the date of the last commit

https://git.computecanada.ca/nix/ccpkgs/commits/cc-18.03-ci-34601
https://git.computecanada.ca/nix/ccpkgs/commit/ec82d1ae521c24ffa96e7bdb9a623e1d10e6a8b6
